<a href="https://colab.research.google.com/github/tanusharma22/tt/blob/machinelearning/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import random



In [0]:
print("enter dimension in form rows*coloumn")
l=input()
lis=[]
lis=[l[i:i+1] for i in range(0, len(l), 1)]
print(lis)

enter dimension in form rows*coloumn
3*4
['3', '*', '4']


In [0]:

c=int(lis[2])
r=int(lis[0])



In [0]:
arr=np.random.randint(0,10,size=(r,c))
print(arr)

[[1 0 9 2]
 [8 8 3 5]
 [2 8 7 1]]


In [0]:
f=open("nump.txt","w")
f.write('array:/n')
np.savetxt(f,arr,fmt='%d')
 